[project]
name = "kakao-empathy-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mangum>=0.20.0",
    "mcp[cli]>=1.25.0",
]
